name: "Humicon HA Connector"
description: "Smart HA integration for Humicon via EW11 (Modbus RS485)"
version: "1.1.3"
slug: "humicon_ha_connector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  ew11_host: ""
  ew11_port: 8899
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: ""
  language: "ko"
schema:
  ew11_host: str
  ew11_port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  language: list(ko|en)
